services:
  postgres:
    image: postgres:latest
    container_name: PostgresDB
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data_db:/var/lib/postgresql

volumes:
  postgres_data_db: